# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


# Ejercicios- Notebook 5
## 1. Arreglo de ceros de longitud 12


In [ ]:
import numpy as np

arreglo = np.zeros(12)
print(arreglo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##2. Arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [ ]:
# Arreglo de ceros de longitud 10
arreglo = np.zeros(10)

# Asignar el valor 10 en la posición número 5 (índice 4, porque Python empieza en 0)
arreglo[4] = 10

print(arreglo)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


## 3. Arreglo que tenga los números del 10 al 49 (inclusive)

In [ ]:
arreglo = np.arange(10,50)
print(arreglo)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 4. Arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [ ]:
# Crear un arreglo de 9 elementos del 0 al 8
arreglo_2d = np.arange(9)

#Convertirlo en una matriz de 3x3
arreglo_2d = arreglo_2d.reshape(3,3)

print(arreglo_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 5. Arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [ ]:
#Crear un arreglo aleatorio de longitud 100
arreglo_aleatorio = np.random.rand (100)

# Imprimir los 100 números aleatorios
print("Números aleatorios:")
print(arreglo_aleatorio)

# Calcular la media
media = np.mean(arreglo_aleatorio)

# Calcular la varianza
varianza = np.var(arreglo_aleatorio)

# Mostrar los resultados
print("Media:", media)
print("Varianza:", varianza)


Números aleatorios:
[3.19668705e-01 2.19579801e-01 8.12480477e-01 7.62065365e-01
 6.21932061e-01 3.97187666e-01 2.19620877e-01 1.72946296e-01
 9.21482134e-01 7.78011314e-01 2.93265290e-01 8.16826526e-01
 8.25250653e-01 8.86303149e-01 2.14327112e-01 3.15289802e-01
 8.01885758e-01 3.80508865e-01 3.04095248e-01 4.44124065e-01
 3.85306234e-01 3.18270506e-01 1.04998628e-01 8.52442279e-01
 1.61079053e-01 2.39768518e-01 1.14325882e-01 8.07706356e-03
 2.77039046e-01 2.29207970e-01 7.24529823e-01 4.53659127e-01
 6.55478629e-01 5.74498143e-01 3.52231953e-01 7.57075859e-01
 7.67945193e-02 1.14295071e-01 7.40973644e-01 5.23049556e-01
 8.83749761e-01 5.29467222e-01 6.98881362e-01 9.89363163e-02
 9.59070723e-01 2.00895875e-01 6.51213232e-01 6.69432460e-01
 7.52527720e-01 2.11042742e-01 1.06329028e-02 7.75458478e-01
 5.57635543e-02 6.49495600e-01 4.16371774e-01 1.98273462e-01
 7.75016208e-03 7.38318557e-01 5.05816808e-01 3.86440733e-01
 1.12596062e-01 5.23597433e-01 3.63880256e-01 9.78041547e-01
 4.6

## 6. Media de un arreglo usando np.sum



In [ ]:
# Crear un arreglo
arreglo_01 = np.array([10, 20, 30, 40, 50])

# Calcular la media usando np.sum
media = np.sum(arreglo_01) / len(arreglo_01)

# Mostrar el resultado
print("Media:", media)

Media: 30.0


## 7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [ ]:
#Crear un arreglo
arreglo_02 = np.array([50, 20, 30, 40, 60])

#Calcular la varianza con np.sum y np.mean
# Paso 1: Calcular la media
media = np.mean(arreglo_02)

# Paso 2: Calcular las diferencias al cuadrado
diferencias_cuadrado = (arreglo_02 - media) ** 2

# Paso 3: Calcular la varianza usando np.sum
varianza = np.sum(diferencias_cuadrado) / len(arreglo_02)

# Resumido sería: varianza = np.mean((arreglo_02 - np.mean(arreglo_02)) ** 2)

#Mostrar el resultado
print("Varianza:", varianza)

Varianza: 200.0


## 8. Array de números aleatorios usando np.random.randn.

In [ ]:
#Crear un arreglo aleatorio de longitud 6
arreglo_aleatorio = np.random.rand (6)

# Imprimir los 100 números aleatorios
print("Números aleatorios:")
print(arreglo_aleatorio)

Números aleatorios:
[0.95382545 0.87535198 0.78001784 0.59425229 0.28010871 0.53125038]
